### ISSUE TITLE
result is null

### ISSUE THREAD

**Issue by berthojoris** [yusriltakeuchi/Tubles#1]
Pas ane test di emulator error kek gini bro
```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty)
```
Pas direction atau scroll di list view bengkelnya

Error line : maps_provider.dart line 333

**Comment by berthojoris** [comment]
Keknya bermasalah di **setPolyLines**

**Comment by yusriltakeuchi** [comment]
Apa Direction API dan Place API di Google Cloudnya sudah dienable? Karena dia perlu service tersebut.

**Comment by berthojoris** [comment]
Sudah semua enable bro. Cuma gak dapat. Pas ane trace, di bagian **void setPolyLines** hasil **result** null. Makanya gak bisa `result.forEach`.  Ane liat di code bro kan checknya `if (result.isNotEmpty)` di ane langsung berenti di situ, kalo ane ganti jadi `if (result != null)` jalan gak error. Cuma polyline nya gak ada coz null

**Comment by berthojoris** [comment]
Sepertinya karen harus mengaktifkan billing

**Comment by yusriltakeuchi** [comment]
Error ini karena tidak berhasil mendapatkan Direction dari Direction APInya Google API, pastiin sudah mengaktifkan billing dan enable Direction APInya.
Karena function tersebut akan mengarah ke HTTP Request berikut

https://maps.googleapis.com/maps/api/directions/json

**Comment by berthojoris** [comment]
Betul mas. Karena billing harus di enable dulu baru jalan

**Comment by yusriltakeuchi** [comment]
Oke berarti solve ya problem ini. Jika ada kendala lagi bisa langsung create new issue lagi aja.
