### ISSUE TITLE
Error TublesItems swipe to fast

### ISSUE THREAD

**Issue by berthojoris** [yusriltakeuchi/Tubles#2]
Jadi kasusnya pas ane swipe TublesItems terlalu cepat sebelum `setPolyLines` berhasil di apply di item sebelumnya. Jadinya langsung jadi error di layar dia otomatis swipe gak berenti dan jika navigasi dipilih maka langsung error
```
Exception has occurred.
_AssertionError ('package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.)
```
Mungkin sebaiknya di bikin block (TublesItems) pake `CircularProgressIndicator` sampai `setPolyLines` jalan dan route dibuatkan baru di release lagi `TublesItems` nya buat di swipe

Ane sih udah record video step2nya

**Comment by yusriltakeuchi** [comment]
Makasi laporan issuenya mas. Mungkin video yang direcord bisa disharing sebagai pembanding?

**Comment by berthojoris** [comment]
Ane udah coba fix pake cara sendiri mas

Trik yg ane pake itu 

- Set loading indicator `bool _loadingIndicator = false;` di `MapProvider`
- Di `void setPolyLines` ane set `_loadingIndicator = true;` trus di set `false` lagi setelah `notifyListeners`
- Bikin 1 container buat loading messagenya
- `Widget _tublesChild` ane bungkus pake widget `Visibility` lalu check provider statusnya `false` atau `true` lalu tampilin loading messagenya

Hasilnya : https://drive.google.com/file/d/1ALttKRv21Ij0euyct8Uix9dNe-O6gxB3/view

Jadi buat prevent scroll lagi ketika sedang finding route. Gak tau ini solusi bagus apa enggak ^_^

Baru mulai coba2 d flutter dan ketemu sample dari mas lalu coba2 oprek
