### ISSUE TITLE
Error build gradle

### ISSUE THREAD

**Issue by MashudiSudonym** [yusriltakeuchi/Tubles#3]
saya mendapatkan error seperti ini saat menjalankan flutter run
`PS C:\Users\muham\StudioProjects\Tubles> flutter run -v
[  +54 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +158 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 8af6b2f038c1172e61d418869363a28dffec3cb4
[   +1 ms] executing: [C:\flutter\flutter/] git tag --contains HEAD
[ +588 ms] Exit code 0 from: git tag --contains HEAD
[   +2 ms] 1.17.5
[  +28 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +77 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +247 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[ +160 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +9 ms] stable
[ +110 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +65 ms] executing: C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +96 ms] List of devices attached
           50ca3077               device product:onc model:Redmi_7 device:onc transport_id:1
[  +17 ms] C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 50ca3077 shell getprop
[ +147 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +234 ms] Found plugin flutter_plugin_android_lifecycle at
C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[  +46 ms] Found plugin google_maps_flutter at
C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.28+1\
[  +20 ms] Found plugin location at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[ +167 ms] Found plugin flutter_plugin_android_lifecycle at
C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.8\
[  +27 ms] Found plugin google_maps_flutter at
C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.28+1\
[  +19 ms] Found plugin location at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[ +177 ms] Generating
C:\Users\muham\StudioProjects\Tubles\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +158 ms] ro.hardware = qcom
[ +161 ms] Launching lib\main.dart on Redmi 7 in debug mode...
[  +34 ms] C:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\muham\AppData\Local\Temp\flutter_tool.64b112ce-ce31-11ea-aea7-f82fa8e40ff8\app.dill --packages
C:\Users\muham\StudioProjects\Tubles\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +53 ms] executing: C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 50ca3077 shell -x logcat -v
time -t 1
[ +261 ms] Exit code 0 from: C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe -s 50ca3077 shell -x logcat
-v time -t 1
[   +4 ms] --------- beginning of main
           07-25 11:43:36.000 D/        (  810): DpmQmiMgr areAllIfaceActive
[  +42 ms] <- compile package:tubles/main.dart
[  +33 ms] executing: C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +74 ms] Android Debug Bridge version 1.0.41
           Version 30.0.3-6597393
           Installed as C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +7 ms] executing: C:\Users\muham\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +110 ms] Building APK
[ +267 ms] Running Gradle task 'assembleDebug'...
[  +49 ms] gradle.properties already sets `android.enableR8`
[  +23 ms] Using gradle from C:\Users\muham\StudioProjects\Tubles\android\gradlew.bat.
[  +12 ms] C:\Users\muham\StudioProjects\Tubles\android\gradlew.bat mode: 33279 rwxrwxrwx.
[ +130 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +721 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +35 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[  +16 ms] executing: [C:\Users\muham\StudioProjects\Tubles\android/]
C:\Users\muham\StudioProjects\Tubles\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64
-Ptarget=C:\Users\muham\StudioProjects\Tubles\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+15562 ms] Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
[+31821 ms] FAILURE: Build failed with an exception.
[ +226 ms] * Where:
[  +20 ms] Build file 'C:\Users\muham\StudioProjects\Tubles\android\app\build.gradle' line: 24
[   +1 ms] * What went wrong:
[   +1 ms] A problem occurred evaluating project ':app'.
[   +1 ms] > Failed to apply plugin [id 'com.android.application']
[  +14 ms]    > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try
editing the distributionUrl in C:\Users\muham\StudioProjects\Tubles\android\gradle\wrapper\gradle-wrapper.properties to
gradle-5.4.1-all.zip
[  +15 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +5 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 45s
[ +312 ms] Running Gradle task 'assembleDebug'... (completed in 48,9s)
[  +10 ms] Exception: Gradle task assembleDebug failed with exit code 1
[  +16 ms] "flutter run" took 51.582ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

PS C:\Users\muham\StudioProjects\Tubles>`

padahal saya cuma nambahin token sesuai dengan README yang dibuat

**Comment by yusriltakeuchi** [comment]
Sepertinya Anda harus melakukan upgrade gradle version diprojectmu, dari error yang didapat terlihat masalahnya karena ini

[ +14 ms] > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try
editing the distributionUrl in C:\Users\muham\StudioProjects\Tubles\android\gradle\wrapper\gradle-wrapper.properties to
gradle-5.4.1-all.zip

Silahkan update dari 4.10.2 ke 5.4.1

**Comment by MashudiSudonym** [comment]
berarti anda harus mengupdate gradle yang ada di project ini karena sudah tidak relevan versinya

**Comment by yusriltakeuchi** [comment]
Yap, karena ini project dibuat pakai versi stable 1.17.1 dan belum diperbarui lagi fiturnya.
Tapi apa dengan mengupdate gradle, project tubles di komputer mas bisa jalan?

**Comment by MashudiSudonym** [comment]
saya menggunakan flutter versi stable 1.17.5
ya dengan mengubah file 
`Tubles/android/gradle/wrapper/gradle-wrapper.properties` 
pada baris 
`distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip`
 menjadi 
`distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

project sudah bisa dijalankan.

**Comment by yusriltakeuchi** [comment]
Thanks atas reportnya, nanti akan saya update git ini agar support untuk versi paling baru.
